# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TP011V3kiqRU6JGU_b4xZC2kynx9Lktw
"""

import streamlit as st
from fpdf import FPDF
from datetime import datetime

# Constantes de calibração
ndw = 4.941
kq_6MV = 0.9918
kq_10MV = 0.9787

# Classe do PDF
class PDF(FPDF):
    def header(self):
        self.set_font("Arial", size=12)
        self.cell(0, 10, "Relatório de Cálculo de Dose (Controle de Qualidade de Paciente Específico)", ln=True, align="C")
        self.ln(5)

    def tabela_dados(self, dados_paciente, campos):
        self.set_font("Arial", size=10)
        for chave, valor in dados_paciente.items():
            self.cell(50, 8, f"{chave}:", border=0)
            self.cell(0, 8, str(valor), border=0, ln=True)
        self.ln(5)

        # Cabeçalho da tabela
        self.set_font("Arial", 'B', 9)
        colunas = ['Campo', 'Energia (MV)', 'Kq', 'Leitura (nC)', 'Dose Planejada (cGy)',
                   'Dose Encontrada (cGy)', 'Diferença (%)']
        larguras = [25, 25, 15, 30, 35, 35, 25]
        for i in range(len(colunas)):
            self.cell(larguras[i], 10, colunas[i], 1, 0, 'C')
        self.ln()

        # Dados dos campos
        self.set_font("Arial", size=9)
        for campo in campos:
            self.cell(larguras[0], 10, campo['nome'], 1, 0, 'C')
            self.cell(larguras[1], 10, str(campo['energia']), 1, 0, 'C')
            self.cell(larguras[2], 10, f"{campo['kq']:.4f}", 1, 0, 'C')
            self.cell(larguras[3], 10, f"{campo['leitura']:.2f}", 1, 0, 'C')
            self.cell(larguras[4], 10, f"{campo['planejada']:.1f}", 1, 0, 'C')
            self.cell(larguras[5], 10, f"{campo['encontrada']:.1f}", 1, 0, 'C')
            self.cell(larguras[6], 10, f"{campo['diferenca_percentual']:.1f}%", 1, 0, 'C')
            self.ln()

        self.ln(10)
        self.cell(0, 10, f"Data: {datetime.today().strftime('%d/%m/%Y')}", ln=True)
        self.cell(0, 10, "Nome: ________________________       Revisão (Físico): __________________", ln=True)


# Interface do Streamlit
st.set_page_config(page_title="Controle de Dose", layout="centered")
st.title("📋 Cálculo de Dose - Controle de Qualidade de Paciente Específico")

with st.form("formulario"):
    st.header("Dados do Paciente")
    nome = st.text_input("Nome completo do paciente")
    num_id = st.text_input("Número de ID do paciente")
    sitio = st.text_input("Sítio anatômico e lateralidade")
    linac = st.text_input("Acelerador de tratamento")

    st.header("Condições Ambientais")
    T = st.number_input("Temperatura (°C)", format="%.1f")
    P = st.number_input("Pressão (kPa)", format="%.1f")

    num_campos = st.number_input("Número de campos", min_value=1, step=1)

    campos = []
    for i in range(num_campos):
        st.markdown(f"### Campo {i+1}")
        nome_campo = st.text_input(f"Nome do campo {i+1}", key=f"nome_{i}")
        energia = st.selectbox(f"Energia (MV) do campo {i+1}", options=[6, 10], key=f"energia_{i}")
        leitura = st.number_input(f"Leitura de carga (nC) do campo {i+1}", format="%.2f", key=f"leitura_{i}")
        dose_esperada = st.number_input(f"Dose planejada (cGy) do campo {i+1}", format="%.1f", key=f"dose_{i}")

        campos.append({
            "nome": nome_campo,
            "energia": energia,
            "leitura": leitura,
            "dose_esperada": dose_esperada
        })

    enviado = st.form_submit_button("📄 Gerar PDF")

# Processamento e Geração do PDF
if enviado:
    To = 20
    Po = 101.3
    ktp = ((273.2 + T) / (273.2 + To)) * (Po / P)

    dados_paciente = {
        "Nome": nome,
        "ID": num_id,
        "Sítio": sitio,
        "Acelerador": linac,
        "Temperatura (°C)": T,
        "Pressão (kPa)": P,
        "Kt,p": round(ktp, 3),
        "Nd,w (cGy/nC)": ndw
    }

    resultados = []
    for campo in campos:
        kq = kq_6MV if campo["energia"] == 6 else kq_10MV
        dose_encontrada = campo["leitura"] * ndw * kq * ktp
        diferenca = ((dose_encontrada - campo["dose_esperada"]) / campo["dose_esperada"]) * 100

        resultados.append({
            "nome": campo["nome"],
            "energia": campo["energia"],
            "kq": kq,
            "leitura": campo["leitura"],
            "planejada": campo["dose_esperada"],
            "encontrada": dose_encontrada,
            "diferenca_percentual": diferenca
        })

    pdf = PDF()
    pdf.add_page()
    pdf.tabela_dados(dados_paciente, resultados)
    nome_arquivo = f"Relatorio_{num_id}_{nome.replace(' ', '_')}.pdf"
    pdf.output(nome_arquivo)

    with open(nome_arquivo, "rb") as f:
        st.success("✅ PDF gerado com sucesso!")
        st.download_button("📥 Clique aqui para baixar o PDF", f, file_name=nome_arquivo, mime="application/pdf")
