# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TP011V3kiqRU6JGU_b4xZC2kynx9Lktw
"""

import streamlit as st
from fpdf import FPDF
from datetime import datetime

# Constantes de calibração
kq_6MV = 0.9918
kq_10MV = 0.9787

# Classe do PDF
class PDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 16)
        self.cell(0, 12, "Controle de Qualidade (Arco Dinâmico)", ln=True, align="C")
        self.ln(8)

    def footer(self):
        # Distância do rodapé
        self.set_y(-25)
        # Largura desejada do logo
        logo_width = 60
        # Calcula posição X para centralizar
        x_centralizado = (self.w - logo_width) / 2
        # Insere a imagem
        self.image(
            "logo_hospital_de_clínicas.png",
            x=x_centralizado,
            y=self.get_y(),
            w=logo_width
        )

    def tabela_dados(self, dados_paciente, campos):
        self.set_font("Arial", size=10)
        linhas = [f"{chave}: {valor}" for chave, valor in dados_paciente.items()]
        larguras_texto = [self.get_string_width(linha) for linha in linhas]
        largura_bloco = max(larguras_texto)
        x_inicio = (self.w - largura_bloco) / 2
        for linha in linhas:
            self.set_x(x_inicio)
            self.cell(largura_bloco, 8, linha, ln=True, align="L")
        self.ln(8)

        # Cabeçalho da tabela
        self.set_font("Arial", 'B', 9)
        colunas = ['Campo', 'Energia (MV)', 'Kq', 'Leitura (nC)', 'Dose Planejada (cGy)',
                   'Dose Encontrada (cGy)', 'Diferença (%)']
        
        larguras = [25, 25, 15, 30, 35, 35, 25]
        largura_tabela = sum(larguras)
        x_tabela = (self.w - largura_tabela) / 2
        self.set_x(x_tabela)
        
        for i in range(len(colunas)):
            self.cell(larguras[i], 10, colunas[i], 1, 0, 'C')
        self.ln()

        # Dados dos campos
        self.set_font("Arial", size=9)
        for campo in campos:
            self.set_x(x_tabela)
            self.cell(larguras[0], 10, campo['nome'], 1, 0, 'C')
            self.cell(larguras[1], 10, str(campo['energia']), 1, 0, 'C')
            self.cell(larguras[2], 10, f"{campo['kq']:.4f}", 1, 0, 'C')
            self.cell(larguras[3], 10, f"{campo['leitura']:.2f}", 1, 0, 'C')
            self.cell(larguras[4], 10, f"{campo['planejada']:.1f}", 1, 0, 'C')
            self.cell(larguras[5], 10, f"{campo['encontrada']:.1f}", 1, 0, 'C')
            self.cell(larguras[6], 10, f"{campo['diferenca_percentual']:.1f}%", 1, 0, 'C')
            self.ln()

        self.ln(10)
        data_hoje = datetime.today().strftime('%d/%m/%Y')
        texto_final = (
            "Nome: ________________________    "
            "Revisão (Físico): __________________    "
            f"Data: {data_hoje}"
        )
        self.cell(0, 10, texto_final, ln=True, align="C")

# Interface do Streamlit
st.set_page_config(page_title="Controle de Dose", layout="centered")
st.title("📋 Cálculo de Dose - Controle de Qualidade de Paciente Específico")

with st.form("formulario"):
    st.header("Dados do Paciente")
    nome = st.text_input("Nome completo do paciente")
    num_id = st.text_input("Número de ID do paciente")
    sitio = st.text_input("Sítio anatômico e lateralidade")
    linac = st.text_input("Acelerador de tratamento")

    st.header("Dados da Câmara")
    ndw = st.number_input(
        "Valor do Nd,w da câmara (cGy/nC)",
        format="%.3f"
    )
    
    st.header("Condições Ambientais")
    T = st.number_input("Temperatura (°C)", format="%.1f")
    P = st.number_input("Pressão (kPa)", format="%.1f")

    num_campos = st.number_input("Número de campos", min_value=1, step=1)

    campos = []
    for i in range(num_campos):
        st.markdown(f"### Campo {i+1}")
        nome_campo = st.text_input(f"Nome do campo {i+1}", key=f"nome_{i}")
        energia = st.selectbox(f"Energia (MV) do campo {i+1}", options=[6, 10], key=f"energia_{i}")
        leitura = st.number_input(f"Leitura de carga (nC) do campo {i+1}", format="%.2f", key=f"leitura_{i}")
        dose_esperada = st.number_input(f"Dose planejada (cGy) do campo {i+1}", format="%.1f", key=f"dose_{i}")

        campos.append({
            "nome": nome_campo,
            "energia": energia,
            "leitura": leitura,
            "dose_esperada": dose_esperada
        })

    enviado = st.form_submit_button("📄 Gerar PDF")

# Processamento e Geração do PDF
if enviado:
    To = 20
    Po = 101.3
    ktp = ((273.2 + T) / (273.2 + To)) * (Po / P)

    dados_paciente = {
        "Nome": nome,
        "ID": num_id,
        "Sítio": sitio,
        "Acelerador": linac,
        "Temperatura (°C)": T,
        "Pressão (kPa)": P,
        "Kt,p": round(ktp, 3),
        "Nd,w (cGy/nC)": round(ndw, 3)
    }

    resultados = []
    for campo in campos:
        kq = kq_6MV if campo["energia"] == 6 else kq_10MV
        dose_encontrada = campo["leitura"] * ndw * kq * ktp
        diferenca = ((dose_encontrada - campo["dose_esperada"]) / campo["dose_esperada"]) * 100

        resultados.append({
            "nome": campo["nome"],
            "energia": campo["energia"],
            "kq": kq,
            "leitura": campo["leitura"],
            "planejada": campo["dose_esperada"],
            "encontrada": dose_encontrada,
            "diferenca_percentual": diferenca
        })

    pdf = PDF(orientation='L')
    pdf.add_page()
    pdf.tabela_dados(dados_paciente, resultados)
    nome_arquivo = f"Relatorio_{num_id}_{nome.replace(' ', '_')}.pdf"
    pdf.output(nome_arquivo)

    with open(nome_arquivo, "rb") as f:
        st.success("✅ PDF gerado com sucesso!")
        st.download_button("📥 Clique aqui para baixar o PDF", f, file_name=nome_arquivo, mime="application/pdf")
